//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebLab.IntAutenticacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntAutenticacion.IAutenticacion")]
    public interface IAutenticacion {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message LoginAplicacionRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#LoginAplicacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.LoginAplicacionResponse LoginAplicacion(WebLab.IntAutenticacion.LoginAplicacionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message LoginPecasRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#LoginPecas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.LoginPecasResponse LoginPecas(WebLab.IntAutenticacion.LoginPecasRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message LoginPecasRapidoRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#LoginPecasRapido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.LoginPecasRapidoResponse LoginPecasRapido(WebLab.IntAutenticacion.LoginPecasRapidoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message LoginJossoRapidoRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#LoginJossoRapido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.LoginJossoRapidoResponse LoginJossoRapido(WebLab.IntAutenticacion.LoginJossoRapidoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message LoginJossoRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#LoginJosso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.LoginJossoResponse LoginJosso(WebLab.IntAutenticacion.LoginJossoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message VerificarSesionActivaPecasRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#VerificarSesionActivaPecas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.VerificarSesionActivaPecasResponse VerificarSesionActivaPecas(WebLab.IntAutenticacion.VerificarSesionActivaPecasRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message ObtenerUserNameDeSesionRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#ObtenerUserNameDeSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.ObtenerUserNameDeSesionResponse ObtenerUserNameDeSesion(WebLab.IntAutenticacion.ObtenerUserNameDeSesionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message FijarBaseDeSesionRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#FijarBaseDeSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.FijarBaseDeSesionResponse FijarBaseDeSesion(WebLab.IntAutenticacion.FijarBaseDeSesionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message ObtenerBaseDeSesionRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#ObtenerBaseDeSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.ObtenerBaseDeSesionResponse ObtenerBaseDeSesion(WebLab.IntAutenticacion.ObtenerBaseDeSesionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message ObtenerDatosDeSesionRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#ObtenerDatosDeSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.ObtenerDatosDeSesionResponse ObtenerDatosDeSesion(WebLab.IntAutenticacion.ObtenerDatosDeSesionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message ObtenerNivelDeSesionRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#ObtenerNivelDeSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.ObtenerNivelDeSesionResponse ObtenerNivelDeSesion(WebLab.IntAutenticacion.ObtenerNivelDeSesionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message CambiarPasswordRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#CambiarPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.CambiarPasswordResponse CambiarPassword(WebLab.IntAutenticacion.CambiarPasswordRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message ObtenerInvolucradoRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#ObtenerInvolucrado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.ObtenerInvolucradoResponse ObtenerInvolucrado(WebLab.IntAutenticacion.ObtenerInvolucradoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message VerificarSesionActivaPecas_V2Request does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#VerificarSesionActivaPecas_V2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.VerificarSesionActivaPecas_V2Response VerificarSesionActivaPecas_V2(WebLab.IntAutenticacion.VerificarSesionActivaPecas_V2Request request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message LogoutRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.LogoutResponse Logout(WebLab.IntAutenticacion.LogoutRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message ObtenerDuracionSesionRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#ObtenerDuracionSesion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.ObtenerDuracionSesionResponse ObtenerDuracionSesion(WebLab.IntAutenticacion.ObtenerDuracionSesionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message EchoRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#Echo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.EchoResponse Echo(WebLab.IntAutenticacion.EchoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message EncriptarRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#Encriptar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.EncriptarResponse Encriptar(WebLab.IntAutenticacion.EncriptarRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:AutenticacionIntf-IAutenticacion) of message DesencriptarRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:AutenticacionIntf-IAutenticacion#Desencriptar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        WebLab.IntAutenticacion.DesencriptarResponse Desencriptar(WebLab.IntAutenticacion.DesencriptarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAplicacion", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LoginAplicacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        public LoginAplicacionRequest() {
        }
        
        public LoginAplicacionRequest(string Usuario, string Password) {
            this.Usuario = Usuario;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginAplicacionResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LoginAplicacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public LoginAplicacionResponse() {
        }
        
        public LoginAplicacionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginPecas", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LoginPecasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        public LoginPecasRequest() {
        }
        
        public LoginPecasRequest(string Usuario, string Password) {
            this.Usuario = Usuario;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginPecasResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LoginPecasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public LoginPecasResponse() {
        }
        
        public LoginPecasResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TiposWebServices")]
    public partial class CIdSesionPecasBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDSesionField;
        
        private string baseField;
        
        private bool resultadoField;
        
        private string usernameField;
        
        /// <remarks/>
        public string IDSesion {
            get {
                return this.iDSesionField;
            }
            set {
                this.iDSesionField = value;
                this.RaisePropertyChanged("IDSesion");
            }
        }
        
        /// <remarks/>
        public string Base {
            get {
                return this.baseField;
            }
            set {
                this.baseField = value;
                this.RaisePropertyChanged("Base");
            }
        }
        
        /// <remarks/>
        public bool Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:AutenticacionIntf")]
    public partial class TResultadoEcho : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codResultadoField;
        
        private string mensajeResultadoField;
        
        private string resultadoField;
        
        /// <remarks/>
        public int CodResultado {
            get {
                return this.codResultadoField;
            }
            set {
                this.codResultadoField = value;
                this.RaisePropertyChanged("CodResultado");
            }
        }
        
        /// <remarks/>
        public string MensajeResultado {
            get {
                return this.mensajeResultadoField;
            }
            set {
                this.mensajeResultadoField = value;
                this.RaisePropertyChanged("MensajeResultado");
            }
        }
        
        /// <remarks/>
        public string Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TiposWebServices")]
    public partial class TDatosSesionPecas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string baseDeDatosField;
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        public string BaseDeDatos {
            get {
                return this.baseDeDatosField;
            }
            set {
                this.baseDeDatosField = value;
                this.RaisePropertyChanged("BaseDeDatos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:TiposWebServices")]
    public partial class CResultadoLoginJosso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iDSessionField;
        
        private string usernameField;
        
        /// <remarks/>
        public string IDSession {
            get {
                return this.iDSessionField;
            }
            set {
                this.iDSessionField = value;
                this.RaisePropertyChanged("IDSession");
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginPecasRapido", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LoginPecasRapidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Password;
        
        public LoginPecasRapidoRequest() {
        }
        
        public LoginPecasRapidoRequest(string Usuario, string Password) {
            this.Usuario = Usuario;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginPecasRapidoResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LoginPecasRapidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WebLab.IntAutenticacion.CIdSesionPecasBase @return;
        
        public LoginPecasRapidoResponse() {
        }
        
        public LoginPecasRapidoResponse(WebLab.IntAutenticacion.CIdSesionPecasBase @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginJossoRapido", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LoginJossoRapidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string IDSession;
        
        public LoginJossoRapidoRequest() {
        }
        
        public LoginJossoRapidoRequest(string IDSession) {
            this.IDSession = IDSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginJossoRapidoResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LoginJossoRapidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WebLab.IntAutenticacion.CIdSesionPecasBase @return;
        
        public LoginJossoRapidoResponse() {
        }
        
        public LoginJossoRapidoResponse(WebLab.IntAutenticacion.CIdSesionPecasBase @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginJosso", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LoginJossoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string IDSesionJosso;
        
        public LoginJossoRequest() {
        }
        
        public LoginJossoRequest(string IDSesionJosso) {
            this.IDSesionJosso = IDSesionJosso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginJossoResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LoginJossoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WebLab.IntAutenticacion.CResultadoLoginJosso @return;
        
        public LoginJossoResponse() {
        }
        
        public LoginJossoResponse(WebLab.IntAutenticacion.CResultadoLoginJosso @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarSesionActivaPecas", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class VerificarSesionActivaPecasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string IdSesionPecas;
        
        public VerificarSesionActivaPecasRequest() {
        }
        
        public VerificarSesionActivaPecasRequest(string IdSesionPecas) {
            this.IdSesionPecas = IdSesionPecas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarSesionActivaPecasResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class VerificarSesionActivaPecasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public VerificarSesionActivaPecasResponse() {
        }
        
        public VerificarSesionActivaPecasResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUserNameDeSesion", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerUserNameDeSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string IdSesionPecas;
        
        public ObtenerUserNameDeSesionRequest() {
        }
        
        public ObtenerUserNameDeSesionRequest(string IdSesionPecas) {
            this.IdSesionPecas = IdSesionPecas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerUserNameDeSesionResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerUserNameDeSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ObtenerUserNameDeSesionResponse() {
        }
        
        public ObtenerUserNameDeSesionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FijarBaseDeSesion", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class FijarBaseDeSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string IdSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string Base;
        
        public FijarBaseDeSesionRequest() {
        }
        
        public FijarBaseDeSesionRequest(string IdSesion, string Base) {
            this.IdSesion = IdSesion;
            this.Base = Base;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FijarBaseDeSesionResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class FijarBaseDeSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public FijarBaseDeSesionResponse() {
        }
        
        public FijarBaseDeSesionResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerBaseDeSesion", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerBaseDeSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string IdSesion;
        
        public ObtenerBaseDeSesionRequest() {
        }
        
        public ObtenerBaseDeSesionRequest(string IdSesion) {
            this.IdSesion = IdSesion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerBaseDeSesionResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerBaseDeSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ObtenerBaseDeSesionResponse() {
        }
        
        public ObtenerBaseDeSesionResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerDatosDeSesion", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerDatosDeSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        public ObtenerDatosDeSesionRequest() {
        }
        
        public ObtenerDatosDeSesionRequest(string idSesion) {
            this.idSesion = idSesion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerDatosDeSesionResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerDatosDeSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WebLab.IntAutenticacion.TDatosSesionPecas @return;
        
        public ObtenerDatosDeSesionResponse() {
        }
        
        public ObtenerDatosDeSesionResponse(WebLab.IntAutenticacion.TDatosSesionPecas @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerNivelDeSesion", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerNivelDeSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        public ObtenerNivelDeSesionRequest() {
        }
        
        public ObtenerNivelDeSesionRequest(string idSesion) {
            this.idSesion = idSesion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerNivelDeSesionResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerNivelDeSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public ObtenerNivelDeSesionResponse() {
        }
        
        public ObtenerNivelDeSesionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambiarPassword", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class CambiarPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ClaveAnterior;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string ClaveNueva;
        
        public CambiarPasswordRequest() {
        }
        
        public CambiarPasswordRequest(string idSesion, string ClaveAnterior, string ClaveNueva) {
            this.idSesion = idSesion;
            this.ClaveAnterior = ClaveAnterior;
            this.ClaveNueva = ClaveNueva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CambiarPasswordResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class CambiarPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public CambiarPasswordResponse() {
        }
        
        public CambiarPasswordResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerInvolucrado", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerInvolucradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        public ObtenerInvolucradoRequest() {
        }
        
        public ObtenerInvolucradoRequest(string idSesion) {
            this.idSesion = idSesion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerInvolucradoResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerInvolucradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public ObtenerInvolucradoResponse() {
        }
        
        public ObtenerInvolucradoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarSesionActivaPecas_V2", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class VerificarSesionActivaPecas_V2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string IdSesionPecas;
        
        public VerificarSesionActivaPecas_V2Request() {
        }
        
        public VerificarSesionActivaPecas_V2Request(string IdSesionPecas) {
            this.IdSesionPecas = IdSesionPecas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificarSesionActivaPecas_V2Response", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class VerificarSesionActivaPecas_V2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public VerificarSesionActivaPecas_V2Response() {
        }
        
        public VerificarSesionActivaPecas_V2Response(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(string idSesion) {
            this.idSesion = idSesion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerDuracionSesion", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerDuracionSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string idSesion;
        
        public ObtenerDuracionSesionRequest() {
        }
        
        public ObtenerDuracionSesionRequest(string idSesion) {
            this.idSesion = idSesion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerDuracionSesionResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class ObtenerDuracionSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public ObtenerDuracionSesionResponse() {
        }
        
        public ObtenerDuracionSesionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Echo", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class EchoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string texto;
        
        public EchoRequest() {
        }
        
        public EchoRequest(string texto) {
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EchoResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class EchoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public WebLab.IntAutenticacion.TResultadoEcho @return;
        
        public EchoResponse() {
        }
        
        public EchoResponse(WebLab.IntAutenticacion.TResultadoEcho @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Encriptar", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class EncriptarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string texto;
        
        public EncriptarRequest() {
        }
        
        public EncriptarRequest(string texto) {
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncriptarResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class EncriptarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public EncriptarResponse() {
        }
        
        public EncriptarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Desencriptar", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class DesencriptarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string texto;
        
        public DesencriptarRequest() {
        }
        
        public DesencriptarRequest(string texto) {
            this.texto = texto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DesencriptarResponse", WrapperNamespace="urn:AutenticacionIntf-IAutenticacion", IsWrapped=true)]
    public partial class DesencriptarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public DesencriptarResponse() {
        }
        
        public DesencriptarResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutenticacionChannel : WebLab.IntAutenticacion.IAutenticacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticacionClient : System.ServiceModel.ClientBase<WebLab.IntAutenticacion.IAutenticacion>, WebLab.IntAutenticacion.IAutenticacion {
        
        public AutenticacionClient() {
        }
        
        public AutenticacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutenticacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.LoginAplicacionResponse WebLab.IntAutenticacion.IAutenticacion.LoginAplicacion(WebLab.IntAutenticacion.LoginAplicacionRequest request) {
            return base.Channel.LoginAplicacion(request);
        }
        
        public string LoginAplicacion(string Usuario, string Password) {
            WebLab.IntAutenticacion.LoginAplicacionRequest inValue = new WebLab.IntAutenticacion.LoginAplicacionRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            WebLab.IntAutenticacion.LoginAplicacionResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).LoginAplicacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.LoginPecasResponse WebLab.IntAutenticacion.IAutenticacion.LoginPecas(WebLab.IntAutenticacion.LoginPecasRequest request) {
            return base.Channel.LoginPecas(request);
        }
        
        public string LoginPecas(string Usuario, string Password) {
            WebLab.IntAutenticacion.LoginPecasRequest inValue = new WebLab.IntAutenticacion.LoginPecasRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            WebLab.IntAutenticacion.LoginPecasResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).LoginPecas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.LoginPecasRapidoResponse WebLab.IntAutenticacion.IAutenticacion.LoginPecasRapido(WebLab.IntAutenticacion.LoginPecasRapidoRequest request) {
            return base.Channel.LoginPecasRapido(request);
        }
        
        public WebLab.IntAutenticacion.CIdSesionPecasBase LoginPecasRapido(string Usuario, string Password) {
            WebLab.IntAutenticacion.LoginPecasRapidoRequest inValue = new WebLab.IntAutenticacion.LoginPecasRapidoRequest();
            inValue.Usuario = Usuario;
            inValue.Password = Password;
            WebLab.IntAutenticacion.LoginPecasRapidoResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).LoginPecasRapido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.LoginJossoRapidoResponse WebLab.IntAutenticacion.IAutenticacion.LoginJossoRapido(WebLab.IntAutenticacion.LoginJossoRapidoRequest request) {
            return base.Channel.LoginJossoRapido(request);
        }
        
        public WebLab.IntAutenticacion.CIdSesionPecasBase LoginJossoRapido(string IDSession) {
            WebLab.IntAutenticacion.LoginJossoRapidoRequest inValue = new WebLab.IntAutenticacion.LoginJossoRapidoRequest();
            inValue.IDSession = IDSession;
            WebLab.IntAutenticacion.LoginJossoRapidoResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).LoginJossoRapido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.LoginJossoResponse WebLab.IntAutenticacion.IAutenticacion.LoginJosso(WebLab.IntAutenticacion.LoginJossoRequest request) {
            return base.Channel.LoginJosso(request);
        }
        
        public WebLab.IntAutenticacion.CResultadoLoginJosso LoginJosso(string IDSesionJosso) {
            WebLab.IntAutenticacion.LoginJossoRequest inValue = new WebLab.IntAutenticacion.LoginJossoRequest();
            inValue.IDSesionJosso = IDSesionJosso;
            WebLab.IntAutenticacion.LoginJossoResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).LoginJosso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.VerificarSesionActivaPecasResponse WebLab.IntAutenticacion.IAutenticacion.VerificarSesionActivaPecas(WebLab.IntAutenticacion.VerificarSesionActivaPecasRequest request) {
            return base.Channel.VerificarSesionActivaPecas(request);
        }
        
        public string VerificarSesionActivaPecas(string IdSesionPecas) {
            WebLab.IntAutenticacion.VerificarSesionActivaPecasRequest inValue = new WebLab.IntAutenticacion.VerificarSesionActivaPecasRequest();
            inValue.IdSesionPecas = IdSesionPecas;
            WebLab.IntAutenticacion.VerificarSesionActivaPecasResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).VerificarSesionActivaPecas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.ObtenerUserNameDeSesionResponse WebLab.IntAutenticacion.IAutenticacion.ObtenerUserNameDeSesion(WebLab.IntAutenticacion.ObtenerUserNameDeSesionRequest request) {
            return base.Channel.ObtenerUserNameDeSesion(request);
        }
        
        public string ObtenerUserNameDeSesion(string IdSesionPecas) {
            WebLab.IntAutenticacion.ObtenerUserNameDeSesionRequest inValue = new WebLab.IntAutenticacion.ObtenerUserNameDeSesionRequest();
            inValue.IdSesionPecas = IdSesionPecas;
            WebLab.IntAutenticacion.ObtenerUserNameDeSesionResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).ObtenerUserNameDeSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.FijarBaseDeSesionResponse WebLab.IntAutenticacion.IAutenticacion.FijarBaseDeSesion(WebLab.IntAutenticacion.FijarBaseDeSesionRequest request) {
            return base.Channel.FijarBaseDeSesion(request);
        }
        
        public bool FijarBaseDeSesion(string IdSesion, string Base) {
            WebLab.IntAutenticacion.FijarBaseDeSesionRequest inValue = new WebLab.IntAutenticacion.FijarBaseDeSesionRequest();
            inValue.IdSesion = IdSesion;
            inValue.Base = Base;
            WebLab.IntAutenticacion.FijarBaseDeSesionResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).FijarBaseDeSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.ObtenerBaseDeSesionResponse WebLab.IntAutenticacion.IAutenticacion.ObtenerBaseDeSesion(WebLab.IntAutenticacion.ObtenerBaseDeSesionRequest request) {
            return base.Channel.ObtenerBaseDeSesion(request);
        }
        
        public string ObtenerBaseDeSesion(string IdSesion) {
            WebLab.IntAutenticacion.ObtenerBaseDeSesionRequest inValue = new WebLab.IntAutenticacion.ObtenerBaseDeSesionRequest();
            inValue.IdSesion = IdSesion;
            WebLab.IntAutenticacion.ObtenerBaseDeSesionResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).ObtenerBaseDeSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.ObtenerDatosDeSesionResponse WebLab.IntAutenticacion.IAutenticacion.ObtenerDatosDeSesion(WebLab.IntAutenticacion.ObtenerDatosDeSesionRequest request) {
            return base.Channel.ObtenerDatosDeSesion(request);
        }
        
        public WebLab.IntAutenticacion.TDatosSesionPecas ObtenerDatosDeSesion(string idSesion) {
            WebLab.IntAutenticacion.ObtenerDatosDeSesionRequest inValue = new WebLab.IntAutenticacion.ObtenerDatosDeSesionRequest();
            inValue.idSesion = idSesion;
            WebLab.IntAutenticacion.ObtenerDatosDeSesionResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).ObtenerDatosDeSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.ObtenerNivelDeSesionResponse WebLab.IntAutenticacion.IAutenticacion.ObtenerNivelDeSesion(WebLab.IntAutenticacion.ObtenerNivelDeSesionRequest request) {
            return base.Channel.ObtenerNivelDeSesion(request);
        }
        
        public int ObtenerNivelDeSesion(string idSesion) {
            WebLab.IntAutenticacion.ObtenerNivelDeSesionRequest inValue = new WebLab.IntAutenticacion.ObtenerNivelDeSesionRequest();
            inValue.idSesion = idSesion;
            WebLab.IntAutenticacion.ObtenerNivelDeSesionResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).ObtenerNivelDeSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.CambiarPasswordResponse WebLab.IntAutenticacion.IAutenticacion.CambiarPassword(WebLab.IntAutenticacion.CambiarPasswordRequest request) {
            return base.Channel.CambiarPassword(request);
        }
        
        public bool CambiarPassword(string idSesion, string ClaveAnterior, string ClaveNueva) {
            WebLab.IntAutenticacion.CambiarPasswordRequest inValue = new WebLab.IntAutenticacion.CambiarPasswordRequest();
            inValue.idSesion = idSesion;
            inValue.ClaveAnterior = ClaveAnterior;
            inValue.ClaveNueva = ClaveNueva;
            WebLab.IntAutenticacion.CambiarPasswordResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).CambiarPassword(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.ObtenerInvolucradoResponse WebLab.IntAutenticacion.IAutenticacion.ObtenerInvolucrado(WebLab.IntAutenticacion.ObtenerInvolucradoRequest request) {
            return base.Channel.ObtenerInvolucrado(request);
        }
        
        public string ObtenerInvolucrado(string idSesion) {
            WebLab.IntAutenticacion.ObtenerInvolucradoRequest inValue = new WebLab.IntAutenticacion.ObtenerInvolucradoRequest();
            inValue.idSesion = idSesion;
            WebLab.IntAutenticacion.ObtenerInvolucradoResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).ObtenerInvolucrado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.VerificarSesionActivaPecas_V2Response WebLab.IntAutenticacion.IAutenticacion.VerificarSesionActivaPecas_V2(WebLab.IntAutenticacion.VerificarSesionActivaPecas_V2Request request) {
            return base.Channel.VerificarSesionActivaPecas_V2(request);
        }
        
        public bool VerificarSesionActivaPecas_V2(string IdSesionPecas) {
            WebLab.IntAutenticacion.VerificarSesionActivaPecas_V2Request inValue = new WebLab.IntAutenticacion.VerificarSesionActivaPecas_V2Request();
            inValue.IdSesionPecas = IdSesionPecas;
            WebLab.IntAutenticacion.VerificarSesionActivaPecas_V2Response retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).VerificarSesionActivaPecas_V2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.LogoutResponse WebLab.IntAutenticacion.IAutenticacion.Logout(WebLab.IntAutenticacion.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public bool Logout(string idSesion) {
            WebLab.IntAutenticacion.LogoutRequest inValue = new WebLab.IntAutenticacion.LogoutRequest();
            inValue.idSesion = idSesion;
            WebLab.IntAutenticacion.LogoutResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).Logout(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.ObtenerDuracionSesionResponse WebLab.IntAutenticacion.IAutenticacion.ObtenerDuracionSesion(WebLab.IntAutenticacion.ObtenerDuracionSesionRequest request) {
            return base.Channel.ObtenerDuracionSesion(request);
        }
        
        public int ObtenerDuracionSesion(string idSesion) {
            WebLab.IntAutenticacion.ObtenerDuracionSesionRequest inValue = new WebLab.IntAutenticacion.ObtenerDuracionSesionRequest();
            inValue.idSesion = idSesion;
            WebLab.IntAutenticacion.ObtenerDuracionSesionResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).ObtenerDuracionSesion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.EchoResponse WebLab.IntAutenticacion.IAutenticacion.Echo(WebLab.IntAutenticacion.EchoRequest request) {
            return base.Channel.Echo(request);
        }
        
        public WebLab.IntAutenticacion.TResultadoEcho Echo(string texto) {
            WebLab.IntAutenticacion.EchoRequest inValue = new WebLab.IntAutenticacion.EchoRequest();
            inValue.texto = texto;
            WebLab.IntAutenticacion.EchoResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).Echo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.EncriptarResponse WebLab.IntAutenticacion.IAutenticacion.Encriptar(WebLab.IntAutenticacion.EncriptarRequest request) {
            return base.Channel.Encriptar(request);
        }
        
        public string Encriptar(string texto) {
            WebLab.IntAutenticacion.EncriptarRequest inValue = new WebLab.IntAutenticacion.EncriptarRequest();
            inValue.texto = texto;
            WebLab.IntAutenticacion.EncriptarResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).Encriptar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebLab.IntAutenticacion.DesencriptarResponse WebLab.IntAutenticacion.IAutenticacion.Desencriptar(WebLab.IntAutenticacion.DesencriptarRequest request) {
            return base.Channel.Desencriptar(request);
        }
        
        public string Desencriptar(string texto) {
            WebLab.IntAutenticacion.DesencriptarRequest inValue = new WebLab.IntAutenticacion.DesencriptarRequest();
            inValue.texto = texto;
            WebLab.IntAutenticacion.DesencriptarResponse retVal = ((WebLab.IntAutenticacion.IAutenticacion)(this)).Desencriptar(inValue);
            return retVal.@return;
        }
    }
}
