/*
insert license info here
*/
using System;
using System.Collections;

namespace Business.Data.AutoAnalizador
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class CobasC303Item: Business.BaseDataAccess
	{

		#region Private Members
		private bool m_isChanged;

		private int m_idcobasc303item; 
		private string m_itemcobas; 
		private int m_iditemsil; 
		private bool m_habilitado; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public CobasC303Item()
		{
            m_idcobasc303item = 0;
            m_itemcobas = String.Empty;
            m_iditemsil = 0; 
			m_habilitado = false; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public CobasC303Item(
			string iditemcobas, 
			int iditemsil, 
			bool habilitado)
			: this()
		{
            m_itemcobas = iditemcobas;
            m_iditemsil = iditemsil;
			m_habilitado = habilitado;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int IdCobasC303Item
		{
			get { return m_idcobasc303item; }
			set
			{
				m_isChanged |= (m_idcobasc303item != value );
                m_idcobasc303item = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public string  ItemCobas
		{
			get { return m_itemcobas; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for IdCobas", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for IdCobas", value, value.ToString());
				
				m_isChanged |= (m_itemcobas != value); m_itemcobas = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public int IdItemSil
		{
			get { return m_iditemsil; }
			set
			{
				m_isChanged |= (m_iditemsil != value );
                m_iditemsil = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public bool Habilitado
		{
			get { return m_habilitado; }
			set
			{
				m_isChanged |= ( m_habilitado != value ); 
				m_habilitado = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
