/*
insert license info here
*/
using System;
using System.Collections;

namespace Business.Data.Laboratorio
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class DiagnosticoEfector : Business.BaseDataAccess
	{

		#region Private Members
		private bool m_isChanged;

		private int m_idDiagnosticoEfector; 
		private Efector m_idefector; 
		private Cie10 m_idDiagnostico;

        private Usuario m_idusuarioregistro;
        private DateTime m_fecharegistro;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public DiagnosticoEfector()
		{ 
            m_idefector = new Efector();
            m_idDiagnostico = new Cie10();

            m_idusuarioregistro = new Usuario();
            m_fecharegistro = DateTime.MinValue;
        }
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public DiagnosticoEfector(
			Efector idefector, 
			Cie10 idDiagnostico,

            Usuario idusuarioregistro,
            DateTime fecharegistro)
            : this()
		{
			m_idefector = idefector;
            m_idDiagnostico = idDiagnostico;
            m_idusuarioregistro = idusuarioregistro;
            m_fecharegistro = fecharegistro;
        }
        #endregion // End Required Fields Only Constructor

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>
        public int IdDiagnosticoEfector
        {
            get { return m_idDiagnosticoEfector; }
            set
            {
                m_isChanged |= (m_idDiagnosticoEfector != value);
                m_idDiagnosticoEfector = value;
            }

        }

        /// <summary>
        /// 
        /// </summary>
        public Efector IdEfector
		{
			get { return m_idefector; }
			set
			{
				m_isChanged |= ( m_idefector != value ); 
				m_idefector = value;
			}

		}

        public Cie10 IdDiagnostico
        {
            get { return m_idDiagnostico; }
            set
            {
                m_isChanged |= (m_idDiagnostico != value);
                m_idDiagnostico = value;
            }

        }

        public Usuario IdUsuarioRegistro
        {
            get { return m_idusuarioregistro; }
            set
            {
                m_isChanged |= (m_idusuarioregistro != value);
                m_idusuarioregistro = value;
            }

        }

        /// <summary>
        /// 
        /// </summary>
        public DateTime FechaRegistro
        {
            get { return m_fecharegistro; }
            set
            {
                m_isChanged |= (m_fecharegistro != value);
                m_fecharegistro = value;
            }

        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
