/*
insert license info here
*/
using System;
using System.Collections;

namespace Business.Data.Laboratorio
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class MuestraEfector : Business.BaseDataAccess
	{

		#region Private Members
		private bool m_isChanged;

		private int m_idMuestraEfector; 
		private Efector m_idefector; 
		private Muestra m_idmuestra;  
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public MuestraEfector()
		{
            m_idMuestraEfector = 0; 
			m_idefector = new Efector();
            m_idmuestra = new Muestra(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public MuestraEfector(
			Efector idefector, 
			Muestra idmuestra )
			: this()
		{
			m_idefector = idefector;
			m_idmuestra = idmuestra; 
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int IdMuestraEfector
        {
			get { return m_idMuestraEfector; }
			set
			{
				m_isChanged |= (m_idMuestraEfector != value );
                m_idMuestraEfector = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public Efector IdEfector
		{
			get { return m_idefector; }
			set
			{
				m_isChanged |= ( m_idefector != value ); 
				m_idefector = value;
			}

		}

        public Muestra IdMuestra
        {
            get { return m_idmuestra; }
            set
            {
                m_isChanged |= (m_idmuestra != value);
                m_idmuestra = value;
            }

        }
       
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
